version: '3.8'

services:

  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'

  worker:
    build: worker
    volumes:
      - ./worker:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - rabbitmq
  app:
    build: app
    volumes:
      - ./app:/app
    ports:
      - '127.0.0.1:5000:5000'
    depends_on:
      - rabbitmq